### ISSUE TITLE
Wczytywanie danych z parallel corpora i wrapper do modulu translacyjnego

### ISSUE THREAD

**Issue by jszablanowski** [H4kan/past_simple#2]
Należy odpowiednio przetworzyć dane ze zbiorów parallel corpora i wczytać je do modułu translacyjnego.

Moduł translacyjny należy opakować we wrapper, który będzie zawierał wszystkie potrzebne kroki do zbudowania modelu.

**Comment by H4kan** [comment]
Ktos mowil ze w tych setach danych jest duzo jakis "smieci" to jak bedziesz na konkretnym operowall to trzeba to zweryfikowac

**Comment by jszablanowski** [comment]
Można oddzielne issue zrobić do przygotowania danych

**Comment by jszablanowski** [comment]
#4
